// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mymodels.proto

package mymodels

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Subscribe struct {
	App                  string   `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Agents               []string `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents,omitempty"`
	Queues               []string `protobuf:"bytes,3,rep,name=queues,proto3" json:"queues,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscribe) Reset()         { *m = Subscribe{} }
func (m *Subscribe) String() string { return proto.CompactTextString(m) }
func (*Subscribe) ProtoMessage()    {}
func (*Subscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_e47b40523705aad6, []int{0}
}

func (m *Subscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscribe.Unmarshal(m, b)
}
func (m *Subscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscribe.Marshal(b, m, deterministic)
}
func (m *Subscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscribe.Merge(m, src)
}
func (m *Subscribe) XXX_Size() int {
	return xxx_messageInfo_Subscribe.Size(m)
}
func (m *Subscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscribe.DiscardUnknown(m)
}

var xxx_messageInfo_Subscribe proto.InternalMessageInfo

func (m *Subscribe) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *Subscribe) GetAgents() []string {
	if m != nil {
		return m.Agents
	}
	return nil
}

func (m *Subscribe) GetQueues() []string {
	if m != nil {
		return m.Queues
	}
	return nil
}

type Event struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	TopicID              string   `protobuf:"bytes,3,opt,name=topicID,proto3" json:"topicID,omitempty"`
	Application          string   `protobuf:"bytes,4,opt,name=application,proto3" json:"application,omitempty"`
	Data                 *any.Any `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_e47b40523705aad6, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Event) GetTopicID() string {
	if m != nil {
		return m.TopicID
	}
	return ""
}

func (m *Event) GetApplication() string {
	if m != nil {
		return m.Application
	}
	return ""
}

func (m *Event) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type TestEvent struct {
	Somestuff            string   `protobuf:"bytes,1,opt,name=somestuff,proto3" json:"somestuff,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestEvent) Reset()         { *m = TestEvent{} }
func (m *TestEvent) String() string { return proto.CompactTextString(m) }
func (*TestEvent) ProtoMessage()    {}
func (*TestEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_e47b40523705aad6, []int{2}
}

func (m *TestEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestEvent.Unmarshal(m, b)
}
func (m *TestEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestEvent.Marshal(b, m, deterministic)
}
func (m *TestEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestEvent.Merge(m, src)
}
func (m *TestEvent) XXX_Size() int {
	return xxx_messageInfo_TestEvent.Size(m)
}
func (m *TestEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TestEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TestEvent proto.InternalMessageInfo

func (m *TestEvent) GetSomestuff() string {
	if m != nil {
		return m.Somestuff
	}
	return ""
}

func init() {
	proto.RegisterType((*Subscribe)(nil), "mymodels.Subscribe")
	proto.RegisterType((*Event)(nil), "mymodels.Event")
	proto.RegisterType((*TestEvent)(nil), "mymodels.TestEvent")
}

func init() { proto.RegisterFile("mymodels.proto", fileDescriptor_e47b40523705aad6) }

var fileDescriptor_e47b40523705aad6 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcb, 0x6a, 0xf3, 0x30,
	0x10, 0x85, 0x7f, 0xc5, 0xb9, 0xfc, 0x9a, 0xd0, 0x0b, 0x6a, 0x28, 0x4a, 0xe8, 0xc2, 0x78, 0xe5,
	0x42, 0x51, 0x4a, 0x4a, 0xf7, 0x6d, 0x68, 0x09, 0x5d, 0x04, 0x42, 0xda, 0x17, 0x90, 0x9d, 0x89,
	0x31, 0xd8, 0x96, 0x6a, 0xc9, 0xa5, 0x7e, 0x92, 0xbe, 0x6e, 0x89, 0x94, 0x4b, 0x77, 0xe7, 0x7c,
	0x3a, 0x1a, 0xce, 0x0c, 0x9c, 0x97, 0x6d, 0xa9, 0x36, 0x58, 0x18, 0xa1, 0x6b, 0x65, 0x15, 0xfb,
	0x7f, 0xf0, 0x93, 0x71, 0xa6, 0x54, 0x56, 0xe0, 0xd4, 0xf1, 0xa4, 0xd9, 0x4e, 0x65, 0xd5, 0xfa,
	0x50, 0xb4, 0x04, 0xfa, 0xde, 0x24, 0x26, 0xad, 0xf3, 0x04, 0xd9, 0x25, 0x04, 0x52, 0x6b, 0x4e,
	0x42, 0x12, 0xd3, 0xf5, 0x4e, 0xb2, 0x6b, 0xe8, 0xcb, 0x0c, 0x2b, 0x6b, 0x78, 0x27, 0x0c, 0x62,
	0xba, 0xde, 0xbb, 0x1d, 0xff, 0x6c, 0xb0, 0x41, 0xc3, 0x03, 0xcf, 0xbd, 0x8b, 0x7e, 0x08, 0xf4,
	0x5e, 0xbf, 0xb0, 0xb2, 0x8c, 0x41, 0xd7, 0xb6, 0x1a, 0xf7, 0xc3, 0x9c, 0x66, 0x23, 0xe8, 0x59,
	0xa5, 0xf3, 0x94, 0x77, 0x1c, 0xf4, 0x86, 0x71, 0x18, 0x38, 0xf1, 0xf6, 0xc2, 0x03, 0xc7, 0x0f,
	0x96, 0x85, 0x30, 0x94, 0x5a, 0x17, 0x79, 0x2a, 0x6d, 0xae, 0x2a, 0xde, 0x75, 0xaf, 0x7f, 0x11,
	0x8b, 0xa1, 0xbb, 0x91, 0x56, 0xf2, 0x5e, 0x48, 0xe2, 0xe1, 0x6c, 0x24, 0xfc, 0xa2, 0xe2, 0xb0,
	0xa8, 0x78, 0xae, 0xda, 0xb5, 0x4b, 0x44, 0xb7, 0x40, 0x3f, 0xd0, 0x58, 0x5f, 0xee, 0x06, 0xa8,
	0x51, 0x25, 0x1a, 0xdb, 0x6c, 0xb7, 0xfb, 0x86, 0x27, 0x30, 0x7b, 0x82, 0xc1, 0xa2, 0x46, 0xb4,
	0x58, 0xb3, 0x47, 0xa0, 0x0b, 0xf4, 0x9f, 0x0c, 0xbb, 0x12, 0xc7, 0x0b, 0x1f, 0x6f, 0x36, 0xb9,
	0x38, 0x41, 0x17, 0x8b, 0xfe, 0xdd, 0x93, 0xf9, 0x1d, 0x8c, 0x73, 0x25, 0xb2, 0x5a, 0xa7, 0x02,
	0xbf, 0x65, 0xa9, 0x0b, 0x34, 0xc7, 0xd8, 0xfc, 0x6c, 0xd9, 0x2e, 0x9d, 0x5a, 0xed, 0x5a, 0xae,
	0x48, 0xd2, 0x77, 0x75, 0x1f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xf4, 0xd3, 0xd6, 0xc1,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	GetEvents(ctx context.Context, in *Subscribe, opts ...grpc.CallOption) (Greeter_GetEventsClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetEvents(ctx context.Context, in *Subscribe, opts ...grpc.CallOption) (Greeter_GetEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/mymodels.Greeter/GetEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterGetEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_GetEventsClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type greeterGetEventsClient struct {
	grpc.ClientStream
}

func (x *greeterGetEventsClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	GetEvents(*Subscribe, Greeter_GetEventsServer) error
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) GetEvents(req *Subscribe, srv Greeter_GetEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Subscribe)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).GetEvents(m, &greeterGetEventsServer{stream})
}

type Greeter_GetEventsServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type greeterGetEventsServer struct {
	grpc.ServerStream
}

func (x *greeterGetEventsServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mymodels.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEvents",
			Handler:       _Greeter_GetEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mymodels.proto",
}
